# baseurl: ""
languageCode: "en-au"
title: "Sarah O'Connor, B.International Relations (Hons.) LLM. International Law. M. Applied Cybernetics"
theme: "lyngs-xmin"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
    post: "/post/:year/:month/:day/:slug/"
    note: "/note/:year/:month/:day/:slug/"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "CV"
      url: "/cv/"
      weight: 2
    - name: "Projects"
      url: "/projects/"
      weight: 3
    - name: "Publications"
      url: "/publications/"
      weight: 4
    - name: "Blog"
      url: "/blog/"
      weight: 5

params:
    description: "Personal website of Sarah O'Connor."
    footer: |
        &copy; Sarah O'Connor 2021. 
        Powered by [Hugo](https://gohugo.io) and [blogdown](https://bookdown.org/yihui/blogdown/). \
        [Source of this website](https://github.com/SarahEOConnor/personal-website).
